server.ssl.key-store = file:/Users/pascal/dev/OpenELIS-Global-2/dev/https/oe_selfsigned.keystore
server.ssl.key-store-password = testtest
server.ssl.key-password = testtest
server.ssl.trust-store=file:/Users/pascal/dev/OpenELIS-Global-2/dev/https/oe_selfsigned.truststore
server.ssl.trust-store-password=testtest

spring.datasource.driver=org.postgresql.Driver
spring.datasource.url= jdbc:postgresql://database:5432/clinlims?currentSchema=clinlims
spring.datasource.username=clinlims
spring.datasource.password=clinlims
spring.jpa.hibernate.ddl-auto=update

hibernate.show_sql=true
hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

org.openelisglobal.server.uri=https://oe.openelis.org:8443/OpenELIS-Global/fhir/
#org.openelisglobal.datasubscriber.uri=https://datasubscriber.openelis.org:8443/subscription/fhirResourceGroup/
#org.openelisglobal.fhirstore.uri=https://host.openelis.org:8444/hapi-fhir-jpaserver/fhir/

#org.openelisglobal.remote.source.uri=https://isanteplusdemo.com/openmrs/ws/fhir2/
#org.openelisglobal.remote.source.uri=https://host.openelis.org:8448/hapi-fhir-jpaserver/
#org.openelisglobal.remote.source.uri=
#org.openelisglobal.task.useBasedOn=true

org.openelisglobal.fhirstore.uri=http://127.0.0.1:8081/fhir/

org.openelisglobal.remote.source.uri=http://185.218.126.190:5001/fhir/
org.openelisglobal.remote.source.updateStatus=true
org.openelisglobal.remote.source.identifier=Practitioner/738185ba-eac9-11e5-8f4d-e06995eac916
org.openelisglobal.task.useBasedOn=true

org.openelisglobal.fhirstore.username=sigdep
org.openelisglobal.fhirstore.password=Sigdep3!
org.openelisglobal.fhir.subscriber.allowHTTP=true


org.openelisglobal.fhir.subscriber=
org.openelisglobal.fhir.subscriber.resources=Task,Patient,ServiceRequest

org.openelisglobal.requester.lastName=Dr. Mauritius
org.openelisglobal.requester.firstName=Felix
org.openelisglobal.requester.phone=230 5123 1234

spring.liquibase.contexts= ci_general,ci_regional,ci_TB
#spring.liquibase.contexts= CDIRetroCI
